plugin_repo(
    name = "proto",
    revision = "v0.4.0",
)

plugin_repo(
    name = "rust",
    owner = "odonate",
    revision = "115fac986f9decd866ee122a3a02437443c16f4d",
)

plugin_repo(
    name = "shell",
    revision = "v0.2.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)
