plugin_repo(
    name = "proto",
    revision = "v0.4.0",
)

plugin_repo(
    name = "rust",
    owner = "odonate",
    revision = "75df73d1eb7c01bb0f1c67aac6110fcd75439b0e",
)

plugin_repo(
    name = "shell",
    revision = "v0.2.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)
