plugin_repo(
    name = "proto",
    revision = "v0.4.0",
)

plugin_repo(
    name = "rust",
    owner = "odonate",
    revision = "fb7ed2142bd5533f78cc55a130e4d75d065d53f9",
)

plugin_repo(
    name = "shell",
    revision = "v0.2.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)
