subinclude("///proto//build_defs/sdk")

proto_build_defs(
    name = "rust_proto",
    srcs = ["rust.build_defs"],
    proto_languages = {
        "proto_language": ["rust_proto_language"],
        "grpc_language": ["rust_grpc_language"],
    },
    visibility = ["PUBLIC"],
)
